services:
  ssh-bot:
    container_name: ssh-bot
    image: lifailon/ssh-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .env:/ssh-bot/.env
      - ${SSH_PRIVATE_KEY_PATH_HOST}:/root/.ssh/id_rsa
      - ~/.ssh/known_hosts:/ssh-bot/known_hosts
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"